yucl/ycl0310/urls.py
from django.urls import path
from . import views

app_name = 'ycl0310'
urlpatterns = [
    path('login/', views.login),
    path('get_token/', views.get_token),
    path('add_file/', views.add_file),
    path('delete_down/', views.delete_down),
    path('home/', views.home),
    path('sousuo/', views.sousuo),
    path('open_file_path/', views.open_file_path),
    path('home/see_file/', views.see_file, name='see_file'),
    path('home/image/', views.image, name='image'),
    path('home/txt/', views.txt, name='txt'),
    path('home/video/', views.video, name='video'),
    path('home/download/', views.download, name='download'),
]

yucl/yucl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('app/', include('ycl0310.urls', 'ycl0310'), name='ycl0310'),
    path('admin/', admin.site.urls),
]

yucl/ycl0310/models.py
from django.db import models

yucl/ycl0310/views.py
import os
import time
import requests
from django.shortcuts import render, redirect
from django.http import FileResponse
from django.utils.encoding import escape_uri_path


def login(request):
    return render(request, 'index.html')


def get_token(request):
    username = request.POST['username']
    password = request.POST['password']
    data = {
        "auth": {
            "identity": {
                "methods": [
                    "password"
                ],
                "password": {
                    "user": {
                        "domain": {
                            "name": "default"
                        },
                        "name": username,
                        "password": password
                    }
                }
            },
            "scope": {
                "project": {
                    "domain": {
                        "name": "default"
                    },
                    "name": username
                }
            }
        }
    }
    url = 'http://192.168.174.10:35357/v3/auth/tokens'
    result = requests.post(url, json=data)
    token = result.headers['X-Subject-Token']
    print('获取的token：', token)
    request.session['token'] = token
    return redirect('/app/home/')


def home(request):
    return render(request, 'home.html')


def size_get(num):
    if num < 1024:
        return str(num) + ' ' + 'B'
    elif 1024 <= num < 1024**2:
        x = round(num/1024, 1)
        return str(x) + ' ' + 'KB'
    else:
        x = round(num/(1024**2), 1)
        return str(x) + ' ' + 'MB'


def time_get(num):
    time_local = time.localtime(num)
    dt = time.strftime("%Y-%m-%d %H:%M:%S", time_local)
    return str(dt)


def see_file(request):
    token = request.session.get('token')
    can = 'Object'
    url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can
    headers = {'X-Auth-Token': token}
    param = {'format': 'json'}
    result = requests.get(url, headers=headers, params=param)
    print('查看文件状态码：', result.status_code)
    datas = result.json()
    print(datas)
    dat = []
    for d in datas:
        data = {}
        name = d['name']
        types = d['content_type']
        size = size_get(d['bytes'])
        last_time = d['last_modified']
        data["name"] = name
        data["type"] = types
        data["size"] = size
        data["last_time"] = last_time
        dat.append(data)
    request.session['can'] = can
    request.session['datas'] = datas
    return render(request, 'type.html', {'dat': dat})


def add_file(request):
    token = request.session.get('token')
    can = request.session.get('can')
    file = request.FILES.get('file')
    name = file.name
    s = name.split('.')
    if s[1] == 'png':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'image/png'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'jpeg':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'image/jpeg'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'jpg':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'image/jpeg'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'txt':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'text/plain'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'docx':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'doc':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'application/msword'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'rtf':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'application/rtf'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'pptx':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'application/vnd.openxmlformats-officedocument.presentationml.presentation'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'xls':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'application/vnd.ms-excel'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'xlsx':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'pdf':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'application/pdf'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'mp3':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'audio/mpeg'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif s[1] == 'mp4':
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + name
        headers = {'X-Auth-Token': token, 'content_type': 'video/mp4'}
        data = open(r'D:\swift\upload\\' + name, 'rb')
        result = requests.put(url, headers=headers, data=data)
        print('添加文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    else:
        print("此文件未在可传输文件范围内！！")
        return redirect('/app/home/see_file/')


def delete_down(request):
    token = request.session.get('token')
    can = request.session.get('can')
    headers = {'X-Auth-Token': token}

    if 'delete' in request.POST:
        file = request.POST['file']
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + file
        result = requests.delete(url, headers=headers)
        print('删除文件状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif 'down' in request.POST:
        file = request.POST['file']
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + file
        result = requests.get(url, headers=headers)
        with open('D:\\swift\\download\\' + file, 'wb') as f:
            f.write(result.content)
        print('下载文件状态码：', result.status_code)
        fs = open('D:\\swift\\download\\' + file, 'rb')
        response = FileResponse(fs)
        response['content_type'] = 'application/octet-stream'
        response['Content-Disposition'] = "attachment; filename*=UTF-8''{}".format(escape_uri_path(file))
        return response

    elif 'image_delete' in request.POST:
        image = request.POST['image']
        url = "http://192.168.174.10:8080/v1/AUTH_71cd8dd762de42c683562083704567d4/" + can + '/' + image
        result = requests.delete(url, headers=headers)
        print('删除图片状态码：', result.status_code)
        return redirect('/app/home/see_file/')
    elif 'image_down' in request.POST:
        image = request.POST['image']

yucl/ycl0310/templates/home.html
<!DOCTYPE html>
{% load static %}
<html>

<!-- Head -->
<head>

	<title>主页</title>

	<!-- Meta-Tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- //Meta-Tags -->

	<!-- Style --> <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
	<style type="text/css">
		<link href="css/zy.menu.css" rel="stylesheet" />
			.headerlitooleulsubitem_gray {
				background-Color: White;
				position: absolute;
				border-left: 1px solid #BCD4E5;
				border-right: 1px solid #BCD4E5;
				border-bottom: 1px solid #BCD4E5;
				box-shadow: 0px 0px 5px #BCD4E5;
				width: 230px;
				margin-left: -170px;
				color: Black;
				display: none;
			}
			
			.headerlitooleulsubitem_red {
				background-Color: White;
				position: absolute;
				border-left: 1px solid #E5BCD4;
				border-right: 1px solid #E5BCD4;
				border-bottom: 1px solid #E5BCD4;
				box-shadow: 0px 0px 5px #E5BCD4;
				width: 230px;
				margin-left: -170px;
				color: Black;
				display: none;
			}
			
			.headerlitooleulsubitem_gray>li,
			.headerlitooleulsubitem_red>li {
				height: 45px;
				background-color: White;
				padding: 0px 10px;
				border-bottom: 1px solid #E4ECF3;
				font-size: 14px;
				line-height: 26px;
			}
			
			.headerlitoolelisubitemtitle_gray {
				height: 35px !important;
				line-height: 35px !important;
				background-color: #ECF2F7 !important;
				margin: 0px !important;
				color: #8090A0 !important;
				font-size: 14px;
				font-weight: bold;
				border-bottom: 1px solid #BCD4E5 !important;
			}
			
			.headerlitoolelisubitemtitle_red {
				height: 35px !important;
				line-height: 35px !important;
				background-color: #F7ECF2 !important;
				margin: 0px !important;
				color: #B471A0 !important;
				font-size: 14px;
				font-weight: bold;
				border-bottom: 1px solid #E5BCD4 !important;
			}
			
			.headerlitooleulsubitem_gray>li:hover {
				background-Color: #F4F9FC;
			}
			
			.headerlitooleulsubitem_red>li:hover {
				background-color: #FCF4F9;
			}
			
			.ulsubitemitems>li {
				float: left;
				height: 20px;
				font-size: 13px;
				font-weight: normal !important;
				color: #555 !important;
			}
			
			.ulsubitemitems>li:last-child {
				clear: both;
				width: 100%;
				height: 10px;
				margin-top: 8px;
				background-color: #DADADA;
			}
			
			.headerlitools_info {
				background-color: #0a318d;
				height: 45px;
				padding: 0px 10px;
				width: 135px;
			}
			
			.headeruserface {
				background-image: url('/content/resources/images/logo.png');
				width: 40px;
				height: 40px;
				background-color: white;
				margin: 2px 10px 2px 2px;
				border-radius: 20px;
				float: left;
			}
			
			.headerlitools_ulinfo {
				background-Color: white;
				border-left: 1px solid #D1D1D1;
				border-right: 1px solid #D1D1D1;
				border-bottom: 1px solid #D1D1D1;
				box-shadow: 0px 0px 5px #D1D1D1;
				width: 160px;
				margin-left: -20px;
				color: Black;
				display: none;
			}
			
			.headerlitools_ulinfo>li {
				height: 35px;
				background-color: White;
				padding: 0px 10px;
				font-size: 14px;
				line-height: 36px;
			}
			
			.headerlitools_ulinfo>li:hover {
				background-Color: #FEE188;
			}
			
			.dvcontent {
				margin: 30px auto 0px auto;
				overflow: auto;
			}
			
			.dvpagerecord {
				padding: 6px 12px;
				background-color: #EAEFF2;
				color: #13a1fc;
				float: left;
				border: 1px solid #D9D9D9;
				text-decoration: underline;
				font-size: 14px;
				cursor: pointer;
			}
			
			.dvpagerecord:hover {
				cursor: pointer;
			}
			
			.dvpagerecord:hover i {
				text-decoration: underline;
			}
			
			.ulpageRecord {
				max-width: 165px;
				float: left;
				white-space: nowrap;
				overflow: hidden;
				margin: 0px;
				padding: 0px;
			}
			
			.ulpageRecord li {
				margin: 0px;
				padding: 6px 12px;
				background-color: #EAEFF2;
				color: #2283C5;
				display: inline-block;
				font-size: 14px;
				border: 1px solid #D9D9D9;
			}
			
			.ulpageRecord li:hover {
				text-decoration: underline;
				cursor: pointer;
			}
			
			.currentPage {
				background-color: #2468a9 !important;
				color: white !important;
			}
			
			#warn {
				width: 300px;
			}
			
			#warn tr {
				width: 300px;
				height: 20px;
			}
			
			#warn tr td {
				width: 90px;
				height: 20px;
				text-align: center;
			}
			
		</style>



</head>
<!-- //Head -->

<!-- Body -->
<body>
	<h1>swift网盘</h1>
	<div style="position:absolute; left:1800px; top:20px">
		<form action="/app/login/">
			<input name="guanji" type="image" src="{% static 'images/guanji.png' %}" style="width:70px; height:70px">
		</form>
	</div>
	<div class="container w3layouts agileits">
		<div class="login w3layouts agileits">
			<input type="text" style="font-size: 1.6em;" value="swift网盘系统" disabled="disabled">
		</div>
		<div class="register w3layouts agileits">
			<input type="text" style="font-size: 1.6em;" value="admin" disabled="disabled">
		</div>
	</div>

	<div class="container w3layouts agileits";  style="height: 620px; width: 1500px;">

		<div class="dvcontent">

			<ul>
				<li>
					<ul class="login w3layouts agileits">
						<a href="{% url 'ycl0310:see_file' %}" target="right">
							<li style="font-size: 20px; margin-top:60px;">文件管理</li>
						</a>
						<a href="{% url 'ycl0310:image' %}" target="right">
							<li style="font-size: 20px;margin-top:40px;">图片管理</li>
						</a>
						<a href="{% url 'ycl0310:txt' %}" target="right">
							<li style="font-size: 20px;margin-top:40px;">文档管理</li>
						</a>
						<a href="{% url 'ycl0310:video' %}" target="right">
							<li style="font-size: 20px;margin-top:40px;">影视管理</li>
						</a>
						<a href="{% url 'ycl0310:download' %}" target="right">
							<li style="font-size: 20px;margin-top:40px;">下载管理</li>
						</a>
					</ul>
					</ul>
				</li>
			</ul>
			<div style="position: absolute; left: 320px; right: 320px;">
				<iframe src="see_file/" scrolling="auto"  width="100%" height="570" name="right" border="none"></iframe>
			</div>
			
		</div>
		<script src="{% static 'js/jquery-1.7.2.min.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/Jqueryplugs.js' %}" type="text/javascript"></script>
		<script src="{% static 'js/_layout.js' %}"></script>
		<div class="clear"></div>

	</div>
	<div style="text-align:center;">

	</div>

</body>
<!-- //Body -->

</html>

yucl/ycl0310/templates/image.html
<!DOCTYPE html>
{% load static %}
<html>

	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" />
		<link rel="stylesheet" href="{% static 'css/Site.css' %}" />
		<link rel="stylesheet" href="{% static 'css/zy.all.css' %}" />
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/amazeui.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/admin.css' %}" />
		<style>
			body{
				overflow: auto;
			}
		</style>
	<body>
		<div class="dvcontent">

			<div>
				<!--tab start-->
				<div class="tabs">
					<div class="hd">
						<ul style="">
							<li style="box-sizing: initial;-webkit-box-sizing: initial;" class="on">图片文件</li>
							<form action="">
								<div style="position:absolute; left:890px; top:2px">
									<input type="text">
								</div>
								<div style="position:absolute; left:1070px; top:0px">
									<input type="submit" value="搜索">
								</div>
							</form>
						</ul>
					</div>
					<div class="bd">
						<ul style="display: block;padding: 20px;">
							<li>
								<!--分页显示角色信息 start-->
								<div id="dv1">

										<table class="table" id="tbRecord">
										<thead>
											<tr>
												<th>文件</th>
												<th>类型</th>
												<th>大小</th>
												<th>时间</th>
												<th>下载</th>
												<th>删除</th>
											</tr>
										</thead>
										<tbody>
											{% for r in image %}
											<form action="/app/delete_down/" method="post">
											{% csrf_token %}
												<tr>
												<input type="text" name="image" value="{{r.name}}" style="display:none">
												<td>{{r.name}}</td>
												<td>{{r.type}}</td>
												<td>{{r.size}}</td>
												<td>{{r.last_time}}</td>
												<td class="edit"><button type="submit" name="image_down"><i class="icon-edit bigger-120"></i>下载</button></td>
												<td class="delete"><button type="submit" name="image_delete"><i class="icon-trash bigger-120"></i>删除</button></td>
											</tr>
											</form>
											{% endfor %}
										</tbody>
									</table>

								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>

			
			<script src="{% static 'js/jquery-1.7.2.min.js' %}" type="text/javascript"></script>
			<script src="{% static 'js/Jqueryplugs.js' %}" type="text/javascript"></script>
			<script src="{% static 'js/_layout.js' %}"></script>
			<script src="{% static 'js/jquery.SuperSlide.source.js' %}"></script>
			<script>
				var num = 1;
				$(function() {

				 $(".tabs").slide({ trigger: "click" });

				});


				var btn_save = function() {
					var pid = $("#RawMaterialsTypePageId  option:selected").val();
					var name = $("#RawMaterialsTypeName").val();
					var desc = $("#RawMaterialsTypeDescription").val();
					var ramark = $("#Ramark").val();
					$.ajax({
						type: "post",
						url: "/RawMaterialsType/AddRawMaterialsType",
						data: { name: name, pid: pid, desc: desc, ramark: ramark },
						success: function(data) {
							if(data > 0) {
								$.jq_Alert({
									message: "添加成功",
									btnOktext: "确认",
									dialogModal: true,
									btnOkClick: function() {
										//$("#RawMaterialsTypeName").val("");
										//$("#RawMaterialsTypeDescription").val("");
										//$("#Ramark").val("");
										//page1();
										location.reload();

									}
								});
							}
						}
					});
					alert(t);
				}

				var btn_edit = function(id) {
					$.jq_Panel({
						url: "/RawMaterialsType/EditRawMaterialsType?id=" + id,
						title: "编辑分类",
						dialogModal: true,
						iframeWidth: 500,
						iframeHeight: 400
					});
				}
				var btn_delete = function(id) {
					$.jq_Confirm({
						message: "您确定要删除吗?",
						btnOkClick: function() {
							$.ajax({
								type: "post",
								url: "/RawMaterialsType/DeleteRawMaterialsType",
								data: { id: id },
								success: function(data) {
									if(data > 0) {
										$.jq_Alert({
											message: "删除成功",
											btnOkClick: function() {
												page1();
											}
										});
									}
								}
							});
						}
					});
				}
			</script>

		</div>
	</body>

</html>

yucl/ycl0310/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>

<!-- Head -->
<head>

	<title>登录表单</title>

	<!-- Meta-Tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">

	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- //Meta-Tags -->

	<!-- Style -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">



</head>
<!-- //Head -->

<!-- Body -->
<body>

	<h1>swift网盘</h1>

	<div class="container w3layouts agileits">

		<div class="login w3layouts agileits">
			<h2>登 录</h2>
			<form action="/app/get_token/" method="post">
				{% csrf_token %}
				<input type="text" name="username" placeholder="用户名" required="">
				<input type="password" name="password" placeholder="密码" required="">
				<div class="send-button w3layouts agileits">
					<input type="submit" value="登 录">
				</div>
				<a href="https://www.baidu.com">记住密码?</a>
			</form>
			<div class="clear"></div>
		</div>
		

		<div class="register w3layouts agileits">
			<h2>注 册</h2>
			<form action="#" method="post">
				<input type="text" Name="Name" placeholder="用户名" required="">
				<input type="text" Name="Email" placeholder="邮箱" required="">
				<input type="password" Name="Password" placeholder="密码" required="">
			</form>
			<div class="send-button w3layouts agileits">
				<form>
					<input type="submit" value="免费注册">
				</form>
			</div>
			<div class="clear"></div>
		</div>

		<div class="clear"></div>

	</div>
<div style="text-align:center;">

</div>

</body>
<!-- //Body -->

</html>

yucl/ycl0310/templates/inventory.html
<!DOCTYPE html>
{% load static %}
<html>

	<head>
		<meta charset="UTF-8">
		<title></title>
		<link rel="stylesheet" />
		<link rel="stylesheet" href="{% static 'css/Site.css' %}" />
		<link rel="stylesheet" href="{% static 'css/zy.all.css' %}" />
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/amazeui.min.css' %}" />
		<link rel="stylesheet" href="{% static 'css/admin.css' %}" />
		<style>
			body{
				overflow: auto;
			}
		</style>
	</head>

	<body>
		<div class="dvcontent">

			<div>
				<!--tab start-->
				<div class="tabs">
					<div class="hd">
						<ul>
							<li class="on" style="box-sizing: initial;-webkit-box-sizing: initial;">下载管理</li>
						</ul>
					</div>
					<div class="bd">
						<ul style="display: block;padding: 20px;">
							<li>
								<!--分页显示角色信息 start-->
								<div id="dv1">
									<table class="table" id="tbRecord">
										<thead>
											<tr>
												<th>文件名称</th>
												<th>下载时间</th>
												<th>类型</th>
												<th>文件大小</th>
												<th>打开文件位置</th>
												
											</tr>
										</thead>
										<tbody>
											{% for r in datas %}
											<form action="/app/open_file_path/" method="post">
												{% csrf_token %}
												<tr>
													<input type="text" name="do" value="{{r.name}}" style="display:none">
													<td>{{r.name}}</td>
													<td>{{r.last_time}}</td>
													<td>{{r.type}}</td>
													<td>{{r.size}}</td>
													<td class="edit"><button type="submit"><i class="icon-edit bigger-120"></i>打开</button></td>
												</tr>
											</form>
											{% endfor %}
										</tbody>
									
									</table>
								</div>
								<!--分页显示角色信息 end-->
							</li>
						</ul>
						<ul class="theme-popbod dform" style="display: none;">
								
						</ul>
					</div>
				</div>
				<!--tab end-->

			</div>

			<script src="{% static 'js/jquery-1.7.2.min.js' %}" type="text/javascript"></script>
			<script src="{% static 'js/Jqueryplugs.js' %}" type="text/javascript"></script>
			<script src="{% static 'js/_layout.js' %}"></script>
			<script src="{% static 'js/jquery.SuperSlide.source.js' %}"></script>
			<script>
				var num = 1;
				$(function() {

				 $(".tabs").slide({ trigger: "click" });

				});

	
				var btn_save = function() {
					var pid = $("#RawMaterialsTypePageId  option:selected").val();
					var name = $("#RawMaterialsTypeName").val();
					var desc = $("#RawMaterialsTypeDescription").val();
					var ramark = $("#Ramark").val();
					$.ajax({
						type: "post",
						url: "/RawMaterialsType/AddRawMaterialsType",
						data: { name: name, pid: pid, desc: desc, ramark: ramark },
						success: function(data) {
							if(data > 0) {
								$.jq_Alert({
									message: "添加成功",
									btnOktext: "确认",
									dialogModal: true,
									btnOkClick: function() {
										//$("#RawMaterialsTypeName").val("");
										//$("#RawMaterialsTypeDescription").val("");
										//$("#Ramark").val("");                           
										//page1();
										location.reload();

									}
								});
							}
						}
					});
					alert(t);
				}

				var btn_edit = function(id) {
					$.jq_Panel({
						url: "/RawMaterialsType/EditRawMaterialsType?id=" + id,
						title: "编辑分类",
						dialogModal: true,
						iframeWidth: 500,
						iframeHeight: 400
					});
				}
			</script>

		</div>
	</body>

</html>